name: 자동화 테스트 실행

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Playwright 자동화 테스트
    runs-on: ubuntu-latest
    
    steps:
    - name: 코드 체크아웃
      uses: actions/checkout@v4
    
    - name: 자동화 테스트 실행
      env:
        TEST_ENV: alpha
      run: |
        docker-compose up --build --abort-on-container-exit playwright-tests
    
    - name: 테스트 결과 업로드
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: 테스트-결과
        path: test-results/ 